### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-gui/osgviz-package_set#1]
signals2 is a header-only Boost library and is not included in the CMakeLists.txt. For this reason my build on Ubuntu 18.04 crashes. It is easy to fix with

```
find_package(Boost REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})
```

The error:

```
In file included from /home/smiles-local/infuse/gui/osgviz/src/modules/ManipulationClickHandler/ManipulationClickHandler.cpp:1:0:
/home/smiles-local/infuse/gui/osgviz/src/modules/ManipulationClickHandler/ManipulationClickHandler.h:4:10: fatal error: boost/signals2.hpp: Datei oder Verzeichnis nicht gefunden
 #include <boost/signals2.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/ManipulationClickHandler.dir/build.make:62: recipe for target 'src/CMakeFiles/ManipulationClickHandler.dir/modules/ManipulationClickHandler/ManipulationClickHandler.cpp.o' failed
make[2]: *** [src/CMakeFiles/ManipulationClickHandler.dir/modules/ManipulationClickHandler/ManipulationClickHandler.cpp.o] Error 1
CMakeFiles/Makefile2:326: recipe for target 'src/CMakeFiles/ManipulationClickHandler.dir/all' failed
make[1]: *** [src/CMakeFiles/ManipulationClickHandler.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

@planthaber

**Comment by planthaber** [comment]
This is related to https://github.com/rock-core/gui-osgviz

**Comment by AlexanderFabisch** [comment]
Ups, sorry. :)
